import type { Plan, Project } from '@/generated/prisma/client';
import { extractTechStack, extractTopRules } from './plan-extractor';

export type SkillFiles = {
  implementFeature: string;
  writeTests: string;
  reviewPr: string;
  updateProgress: string;
};

// ─── implement-feature ────────────────────────────────────────────────────────

function buildImplementFeatureSkill(project: Project, plan: Plan): string {
  const techSummary = extractTechStack(plan.architecture);
  const topRules = extractTopRules(plan.rules, 5);

  return [
    '---',
    `description: Implement a new feature end-to-end for ${project.name}`,
    'argument-hint: <feature name or task description>',
    'allowed-tools: Read, Edit, Bash, Grep, Glob',
    'when_to_use: Use when implementing a new feature, user story, or task from the project task list',
    '---',
    '',
    '# Implement Feature: $ARGUMENTS',
    '',
    '## Goal',
    '',
    `Implement the feature described in \`$ARGUMENTS\` completely and correctly for **${project.name}**,`,
    "following the project's established architecture and coding standards.",
    '',
    '## Tech Stack',
    '',
    techSummary,
    '',
    '## Steps',
    '',
    '### 1. Understand the Requirement',
    '',
    '- Find the task in `.init-ai/initial-plan/task.md` and read its description',
    '- Check `.init-ai/initial-plan/prd.md` for user story context and acceptance criteria',
    '- Review any relevant API contracts in `.init-ai/initial-plan/api-spec.md`',
    '',
    '### 2. Explore the Codebase',
    '',
    '- Grep for related existing code to understand current patterns',
    '- Identify which files need to be created or modified',
    '- Check for reusable components, utilities, or patterns to follow',
    '',
    '### 3. Plan Before Coding',
    '',
    '- List every file to create/modify and the change needed in each',
    '- Confirm the approach matches `.init-ai/initial-plan/architecture.md`',
    '- Validate against the rules below before writing any code',
    '',
    '### 4. Implement',
    '',
    '- Follow the tech stack and conventions exactly',
    '- Write code incrementally and verify each piece before continuing',
    '- Reference `.init-ai/initial-plan/api-spec.md` for endpoint contracts',
    '- Reference `.init-ai/initial-plan/db-schema.md` for data models',
    '',
    '### 5. Test',
    '',
    '- Write tests for the new code (unit + integration as appropriate)',
    '- Run the full test suite; fix any failures before declaring done',
    '- Verify the feature works end-to-end against acceptance criteria',
    '',
    '### 6. Update Progress',
    '',
    '- Check off the completed task in `.init-ai/initial-plan/task.md`',
    '- Append a completion note to `.init-ai/context/progress.md`:',
    '  ```',
    '  ## [Date] — Completed: $ARGUMENTS',
    '  - What was implemented',
    '  - Files changed',
    '  - Tests added',
    '  ```',
    '',
    '## Rules (Must Follow)',
    '',
    topRules,
    '',
    '→ Full ruleset: `.init-ai/workspace-config/rules.md`',
  ].join('\n');
}

// ─── write-tests ──────────────────────────────────────────────────────────────

function buildWriteTestsSkill(project: Project, plan: Plan): string {
  const techSummary = extractTechStack(plan.architecture);
  const topRules = extractTopRules(plan.rules, 4);

  return [
    '---',
    `description: Add comprehensive tests for a module or feature in ${project.name}`,
    'argument-hint: <file path, module name, or feature to test>',
    'allowed-tools: Read, Edit, Bash, Grep, Glob',
    'when_to_use: Use when adding unit tests, integration tests, or improving test coverage for a specific module',
    '---',
    '',
    '# Write Tests: $ARGUMENTS',
    '',
    '## Goal',
    '',
    `Write comprehensive, maintainable tests for \`$ARGUMENTS\` in **${project.name}**.`,
    'Tests should verify behavior, serve as documentation, and prevent regressions.',
    '',
    '## Tech Stack',
    '',
    techSummary,
    '',
    '## Steps',
    '',
    '### 1. Read the Code Under Test',
    '',
    '- Read the target file(s) thoroughly before writing any tests',
    '- Understand the public API — inputs, outputs, and side effects',
    '- Identify all meaningful code paths (happy path, edge cases, errors)',
    '',
    '### 2. Check Existing Tests',
    '',
    '- Grep for existing tests to understand the test style used in this project',
    '- Avoid duplicating tests that already provide adequate coverage',
    '',
    '### 3. Write Tests',
    '',
    'For each code path, write a test that:',
    '',
    '- Has a clear, descriptive name (what + expected outcome)',
    '- Is isolated from external dependencies (mock/stub as needed)',
    '- Focuses on a single behavior',
    '- Is deterministic (same result every run)',
    '',
    '**Coverage targets:**',
    '- Happy path: all main scenarios',
    '- Edge cases: empty inputs, boundary values, null/undefined',
    '- Error cases: invalid inputs, service failures, network errors',
    '',
    '### 4. Run and Verify',
    '',
    '- Run the test suite and confirm all tests pass',
    '- Check coverage for the target module if tooling supports it',
    '- Fix any failing tests before declaring done',
    '',
    '### 5. Update Progress',
    '',
    '- Append a note to `.init-ai/context/progress.md`:',
    '  ```',
    '  ## [Date] — Tests Added: $ARGUMENTS',
    '  - Tests written: [count]',
    '  - Coverage: [note if checked]',
    '  ```',
    '',
    '## Rules',
    '',
    topRules,
    '',
    '→ Full ruleset: `.init-ai/workspace-config/rules.md`',
  ].join('\n');
}

// ─── review-pr ────────────────────────────────────────────────────────────────

function buildReviewPrSkill(project: Project, plan: Plan): string {
  const topRules = extractTopRules(plan.rules, 6);

  return [
    '---',
    `description: Review code changes against ${project.name} project rules and standards`,
    'argument-hint: <file path, list of changed files, or description of changes>',
    'allowed-tools: Read, Bash, Grep, Glob',
    'when_to_use: Use when reviewing code for correctness, standards compliance, and architecture fit before merging',
    '---',
    '',
    '# Review Code: $ARGUMENTS',
    '',
    '## Goal',
    '',
    `Review the code changes described by \`$ARGUMENTS\` for **${project.name}** against`,
    "the project's rules, architecture, and quality standards.",
    '',
    '## Steps',
    '',
    '### 1. Understand the Change',
    '',
    '- Read all changed files: `$ARGUMENTS`',
    '- Identify what the change is supposed to accomplish',
    '- Reference `.init-ai/initial-plan/task.md` or `.init-ai/initial-plan/prd.md` for acceptance criteria',
    '',
    '### 2. Correctness',
    '',
    '- Does the implementation match the spec/task requirements?',
    '- Are there logic errors, off-by-one issues, or race conditions?',
    '- Is error handling complete and appropriate?',
    '- Are all inputs validated?',
    '',
    '### 3. Rules Compliance',
    '',
    '**Project rules to enforce:**',
    '',
    topRules,
    '',
    '_Full ruleset: `.init-ai/workspace-config/rules.md`_',
    '',
    '### 4. Architecture Compliance',
    '',
    '- Does the code follow patterns in `.init-ai/initial-plan/architecture.md`?',
    '- Is separation of concerns maintained?',
    '- Are there inappropriate cross-layer dependencies?',
    '',
    '### 5. Tests',
    '',
    '- Are tests included for the changes?',
    '- Do the tests adequately cover the implementation?',
    '- Do existing tests still pass?',
    '',
    '### 6. Report',
    '',
    'Produce a structured review:',
    '',
    '```',
    '## Code Review: $ARGUMENTS',
    '',
    '### Summary',
    '[1–2 sentence summary of what the change does]',
    '',
    '### ✅ Approved Items',
    '[What looks correct and well-implemented]',
    '',
    '### ⚠️ Issues (Must Fix)',
    '[Blocking issues with file:line references and explanations]',
    '',
    '### 💡 Suggestions (Optional)',
    '[Non-blocking improvements]',
    '',
    '### Verdict',
    '[ ] Approved — ready to merge',
    '[ ] Changes requested — see issues above',
    '```',
  ].join('\n');
}

// ─── update-progress ─────────────────────────────────────────────────────────

function buildUpdateProgressSkill(project: Project, _plan: Plan): string {
  return [
    '---',
    `description: Log implementation progress and update the task list for ${project.name}`,
    'argument-hint: <description of what was completed>',
    'allowed-tools: Read, Edit, Bash',
    'when_to_use: Use after completing a task or milestone to keep the project record current',
    '---',
    '',
    '# Update Progress: $ARGUMENTS',
    '',
    '## Goal',
    '',
    `Record the completion of \`$ARGUMENTS\` in **${project.name}**'s progress log and`,
    'update the task list to reflect current status.',
    '',
    '## Steps',
    '',
    '### 1. Update the Task List',
    '',
    'Open `.init-ai/initial-plan/task.md` and:',
    '- Find the task(s) corresponding to `$ARGUMENTS`',
    '- Change `- [ ]` to `- [x]` for each completed task',
    '- Add any newly discovered sub-tasks as new `- [ ]` items',
    '',
    '### 2. Write a Progress Note',
    '',
    'Create or append to `.init-ai/context/progress.md`:',
    '',
    '```markdown',
    '## [YYYY-MM-DD] — $ARGUMENTS',
    '',
    '### Completed',
    '- [List what was built/changed]',
    '',
    '### Files Changed',
    '- [List key files created or modified]',
    '',
    '### Tests',
    '- [Describe tests added, or note if none needed]',
    '',
    '### Notes',
    '- [Any decisions made, blockers, or follow-up work]',
    '',
    '### Next Up',
    '- [Next task(s) from the task list]',
    '```',
    '',
    '### 3. Check Project Status',
    '',
    '- Review remaining tasks in `.init-ai/initial-plan/task.md`',
    '- If all tasks in an epic are done, note the milestone',
    '- If blockers were found, flag them clearly for the next session',
    '',
    '## Reminder',
    '',
    'Always read the current state of `.init-ai/initial-plan/task.md` before making',
    'changes to avoid overwriting concurrent updates.',
  ].join('\n');
}

// ─── Public API ───────────────────────────────────────────────────────────────

export function buildSkillFiles(project: Project, plan: Plan): SkillFiles {
  return {
    implementFeature: buildImplementFeatureSkill(project, plan),
    writeTests: buildWriteTestsSkill(project, plan),
    reviewPr: buildReviewPrSkill(project, plan),
    updateProgress: buildUpdateProgressSkill(project, plan),
  };
}
